-- MySQL Script generated by MySQL Workbench
-- Thu Mar 12 10:52:07 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Categories` (
                                                   `Id` INT NOT NULL AUTO_INCREMENT,
                                                   `Name` VARCHAR(30) NOT NULL,
    `Description` VARCHAR(100) NOT NULL,
    PRIMARY KEY (`Id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Agencies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Agencies` (
                                                 `Id` INT NOT NULL AUTO_INCREMENT,
                                                 `Name` VARCHAR(30) NOT NULL,
    `Address` VARCHAR(30) NOT NULL,
    `City` VARCHAR(30) NOT NULL,
    `Phone` VARCHAR(30) NOT NULL,
    `IBAN` VARCHAR(34) NOT NULL,
    PRIMARY KEY (`Id`),
    UNIQUE INDEX `IBAN_UNIQUE` (`IBAN` ASC) VISIBLE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cars`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cars` (
                                             `Id` INT NOT NULL AUTO_INCREMENT,
                                             `Brand` VARCHAR(50) NOT NULL,
    `Model` VARCHAR(50) NOT NULL,
    `Year` YEAR NOT NULL,
    `License_plate` VARCHAR(30) NOT NULL,
    `Number_of_seats` INT NOT NULL,
    `Max_speed` INT NOT NULL,
    `Fuel_consumption` VARCHAR(30) NOT NULL,
    `Fuel_type` VARCHAR(30) NOT NULL,
    `Price_per_day` FLOAT NOT NULL,
    `Available` TINYINT NOT NULL,
    `Categories_Id` INT NOT NULL,
    `Agencies_Id` INT NOT NULL,
    PRIMARY KEY (`Id`),
    INDEX `fk_Cars_Categories1_idx` (`Categories_Id` ASC) VISIBLE,
    INDEX `fk_Cars_Agencies1_idx` (`Agencies_Id` ASC) VISIBLE,
    CONSTRAINT `fk_Cars_Categories1`
    FOREIGN KEY (`Categories_Id`)
    REFERENCES `mydb`.`Categories` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_Cars_Agencies1`
    FOREIGN KEY (`Agencies_Id`)
    REFERENCES `mydb`.`Agencies` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Customers` (
                                                  `Id` INT NOT NULL AUTO_INCREMENT,
                                                  `First_name` VARCHAR(30) NOT NULL,
    `Last_name` VARCHAR(30) NOT NULL,
    `Password` VARCHAR(254) NOT NULL,
    `Birth_date` DATE NOT NULL,
    `Address` VARCHAR(30) NOT NULL,
    `Email` VARCHAR(30) NOT NULL,
    `Phone` VARCHAR(30) NOT NULL,
    PRIMARY KEY (`Id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Payments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Payments` (
                                                 `Id` INT NOT NULL AUTO_INCREMENT,
                                                 `Amount` FLOAT NOT NULL,
                                                 `Payment_date` DATE NOT NULL,
                                                 `Payment_method` VARCHAR(30) NOT NULL,
    `Payment_status` VARCHAR(30) NOT NULL,
    `Agencies_Id` INT NOT NULL,
    `Customers_Id` INT NOT NULL,
    PRIMARY KEY (`Id`),
    INDEX `fk_Payments_Agencies1_idx` (`Agencies_Id` ASC) VISIBLE,
    INDEX `fk_Payments_Customers1_idx` (`Customers_Id` ASC) VISIBLE,
    CONSTRAINT `fk_Payments_Agencies1`
    FOREIGN KEY (`Agencies_Id`)
    REFERENCES `mydb`.`Agencies` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_Payments_Customers1`
    FOREIGN KEY (`Customers_Id`)
    REFERENCES `mydb`.`Customers` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Rentals`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Rentals` (
                                                `Id` INT NOT NULL AUTO_INCREMENT,
                                                `Start_date` DATE NOT NULL,
                                                `End_date` DATE NOT NULL,
                                                `Total_price` FLOAT NOT NULL,
                                                `Rental_status` VARCHAR(30) NOT NULL,
    `Cars_Id` INT NOT NULL,
    `Customers_Id` INT NOT NULL,
    `Payments_Id` INT NOT NULL,
    PRIMARY KEY (`Id`),
    INDEX `fk_Rentals_Cars1_idx` (`Cars_Id` ASC) VISIBLE,
    INDEX `fk_Rentals_Customers1_idx` (`Customers_Id` ASC) VISIBLE,
    INDEX `fk_Rentals_Payments1_idx` (`Payments_Id` ASC) VISIBLE,
    CONSTRAINT `fk_Rentals_Cars1`
    FOREIGN KEY (`Cars_Id`)
    REFERENCES `mydb`.`Cars` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_Rentals_Customers1`
    FOREIGN KEY (`Customers_Id`)
    REFERENCES `mydb`.`Customers` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_Rentals_Payments1`
    FOREIGN KEY (`Payments_Id`)
    REFERENCES `mydb`.`Payments` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
